### ISSUE TITLE
XcodeColors installed using Alcatraz is not being detected

### ISSUE THREAD

**Issue by falcon4ever** [DaveWoodCom/XCGLogger#116]
When you install XcodeColors using Alcatraz (http://alcatraz.io/) in XCode 7.2, the detection seems to fail, probably because the environment variable isn't being set.

```
// Check if XcodeColors is installed and enabled
if let xcodeColors = NSProcessInfo.processInfo().environment["XcodeColors"] {
   xcodeColorsEnabled = xcodeColors == "YES"
}
```

**Comment by DaveWoodCom** [comment]
Use:

    log.xcodeColorsEnabled = true

when setting up your `log` object to explicitly turn on colours. Relying on the environment variable isn't great for iOS apps since you have to add it manually in your project. The environment variable works better for OS X apps since you can set it in your `.profile` etc and have it work for all projects.
