### ISSUE TITLE
pod 'XCGLogger', '~> 3.2' Not working

### ISSUE THREAD

**Issue by tejas-ardeshna** [DaveWoodCom/XCGLogger#133]
I tries to install XCGLogger for swift 2.1 which was 3.2, i added pod 'XCGLogger', '~> 3.2' line in pod file still its installing 3.3 version.

**Comment by JRG-Developer** [comment]
Have you tried `pod update`?

If you `pod install`, CocoaPods will respect your `Podfile.lock`, which would list `XCGLogger 3.2` if you had previously installed said version.

Alternatively, you can change your version to `~> 3.3` in your `Podfile`, which would force CocoaPods to install the new version (as `3.2` in the `Podfile.lock` would no longer satisfy this requirement).

**Comment by tejas-ardeshna** [comment]
@JRG-Developer  Does XCGLogger 3.3 works with swift 2.1?

**Comment by DaveWoodCom** [comment]
Continue to use XCGLogger 3.2 with Swift 2.1.
The issue is that in your Podfile, you're using the `~>` operator, which means, use versions `3.2` through  `3.9` (see https://guides.cocoapods.org/syntax/podfile.html#pod ). So you have a few options, the two easiest would to change your Podfile to:

    pod 'XCGLogger', '3.2'

Which means use exactly version `3.2`.

Or change it to:

    pod 'XCGLogger', '~> 3.2.0'

Which would mean use versions `3.2.0` through `3.2.9`.

The first option is probably the best since it's highly unlikely there will be any new versions between `3.2` and `3.3`.
