### ISSUE TITLE
swift 3.0

### ISSUE THREAD

**Issue by Bersaelor** [DaveWoodCom/XCGLogger#135]
Dear @DaveWoodCom ,

I use XCGLogger in a number of swift projects and am converting my own [code](https://github.com/Bersaelor/KDTree) to Swift 3 at the moment.
As part of this I created a [swift 3 branch of XCGLogger](https://github.com/Bersaelor/XCGLogger/tree/swift_3.0)

It was mostly straight forward renaming, but I had to remove the queue name logging [here](https://github.com/Bersaelor/XCGLogger/commit/bb7056a501147f6e034b19671ebaba660320efc4#diff-3df547913649b2b1141169aeb407b10cL107).

It appears the previously used `DISPATCH_CURRENT_QUEUE_LABEL ` has been removed and not replaced with anything new. Maybe the current queue is not such an easily defined thing as [some people have been arguing](http://stackoverflow.com/questions/17839812/how-to-dispatch-after-in-the-current-queue).

**Comment by alexiosdev** [comment]
Hi, guys I have forked branch of  XCGLogger  which works in XCode 8.0 beta 3.
Here's link.

[XCGLogger](https://github.com/alexiosdev/XCGLogger/tree/swift3_alex)

**Comment by Gerst20051** [comment]
👍

**Comment by damienrambout** [comment]
👍
A Swift 3 version of this lib would be great!

**Comment by jomnius** [comment]
Is there any "official" version in plans?

**Comment by DaveWoodCom** [comment]
Yes, whole new version coming shortly, tonnes of changes to be more Swift 3 like. Should have the beta pushed in a few hours now.

**Comment by picciano** [comment]
Anxiously anticipating.

**Comment by DaveWoodCom** [comment]
Please see #143 

@st3fan / @alexiosdev Thanks for your branches. I wanted to use the fact that Swift 3 breaks pretty much every project as a way of cleaning up some of the technical debt that has accumulated in this project for a while. A lot of things in Swift have changed since this was originally released and now was a great time to clean up.

Also note, I was able to solve the `DISPATCH_CURRENT_QUEUE_LABEL` issue. Don't know of any other logging library that has done so. :)
