### ISSUE TITLE
Memory leaks in simple XCGLogger.defaultInstance().info("")

### ISSUE THREAD

**Issue by pomozoff** [DaveWoodCom/XCGLogger#137]
Here is the simplest [project](https://github.com/pomozoff/LeakXCGLogger) with one custom line of code, demonstrates three leaks in one line:
`XCGLogger.defaultInstance().info("")`

Run Instruments and you will instantly see three leaks like these:
![2016-07-06_11-11-56](https://cloud.githubusercontent.com/assets/839094/16611531/fcc3759a-4372-11e6-9ec2-32917915757c.png)

**Comment by pomozoff** [comment]
Here are all three lines:
![2016-07-06_11-17-08](https://cloud.githubusercontent.com/assets/839094/16611634/a3be9c6c-4373-11e6-8824-b064c65840de.png)

**Comment by DaveWoodCom** [comment]
Thanks for this. So I spent a tonne of time digging into the memory leaks. The leaks are actually in the Swift core library and our code just happened to trigger them. As you probably noticed, judging by the PR, the leak is triggered in some cases using string interpolation, so changing affected code from: `"[\(owner.identifier)] "` to `"[" + owner.identifier + "] "` avoids the leak.

Worth noting the leaks appear to be fixed in Swift 3.
