### ISSUE TITLE
log.error("\(x)"): Reference to property `x` in closure requires explicit `self.` to make capture semantics explicit

### ISSUE THREAD

**Issue by dusek** [DaveWoodCom/XCGLogger#146]
The title says it all 😄 

After upgrading from 3.3 to 3.5.1, I get a lots of compile errors like the above (`x` is a property of `self`).

Saw it happen with `error`, `warning` and `verbose`.

**Comment by DaveWoodCom** [comment]
In earlier versions the closures were marked as `@noescape` in order to save you from having to write `self.`. However, this was technically incorrect since the closures do in fact escape (they're passed on to other methods to be executed, they're not executed the `debug()` method themselves.

Because the closures escape, they need to be able to capture the variable, which is why you need to include `self.`.

I don't know if there's any other way around it, short of duplicating a tonne of code in the library, or executing the closure early, which could mean it would be executed even when the result would be discarded (seems like a bad trade-off to add a performance hit just to avoid extra typing).

If anyone has a solution I'm not seeing, please speak up.

**Comment by DaveWoodCom** [comment]
Will reopen if anyone has other suggestions.

**Comment by patters** [comment]
Passing a non-escaping closure to another function that takes a non-escaping closure is perfectly legal Swift.

```Swift


func bar(@autoclosure closure: () -> String) {
    print(closure())
}

func foo(@autoclosure closure: () -> String) {
    bar(closure)
}

class Test {
    let x = 1
    
    init() {
    }
    
    func doit() {
        foo("x = \(x)")
    }
}

let t = Test()
t.doit()
```

Since `logln` does not make a copy of the closure (for example, using `dispatch_async`) then no `(escaping)` attributes are required. I've opened #150 which compiles just fine.

**Comment by DaveWoodCom** [comment]
Ok, will change this for the next beta (hopefully out in a few hours). I was probably being overly cautious.

**Comment by DaveWoodCom** [comment]
This now on master, swift_2.2, swift_2.3 and swift_3.0 branches. Thanks!

**Comment by dtrenz** [comment]
Any idea when this will be released to the pod repo?

**Comment by DaveWoodCom** [comment]
Sorry, looks like I broke this again way back in September when merging in a big branch. I've re-fixed it. Currently on the develop branch, will hit master and CocoaPods shortly.
