### ISSUE TITLE
Support for macOS 10.9

### ISSUE THREAD

**Issue by suzukieng** [DaveWoodCom/XCGLogger#206]
Hi @DaveWoodCom 

We are migrating a project to Swift 3 and correspondingly need to update our XCGLogger dependency. Unfortunately we are at the moment still required to run on 10.9, and CocoaPods complains that XCGLogger requires 10.10. Is there any reason why you don't support 10.9? Swift 3 seems to be supported all the way down to 10.6.

Regards,
Alex

**Comment by RabbitMC** [comment]
If you make a Xcode Cocoa Project, setting the deployment Target to 10.6, you will get this error message: 

> Swift is unavailable on macOS earlier than 10.9; please set MACOSX_DEPLOYMENT_TARGET to 10.9 or later (currently it is '10.6').

> CocoaPods complains that XCGLogger requires 10.10.
For XCGLogger, change the [Podspec file](https://github.com/DaveWoodCom/XCGLogger/blob/master/XCGLogger.podspec) at `spec.osx.deployment_target = '10.10'`.

Add your fork as a dev pod to cocoa pods: 
Your Pod File should have this kind of line 

`pod 'MyInternalLibrary', :path => './MyInternalLibrary'`

instead of `pod XCGLogger`.

At the end, if everything works, try to make a pull request to the maintainer of XCGLogger

**Comment by suzukieng** [comment]
@RabbitMC thanks, I know how to fork a library and test stuff out.
@DaveWoodCom we convinced our client to move the deployment target of our application to 10.10, so this is no longer an issue for us. Still, as even Swift 4 will continue to support 10.9, and XCGLogger is a logging framework which I would consider base infrastructure, it might make sense to align the deployment target with Swift. But that's just my two cents.
