### ISSUE TITLE
hi！ Does XCGLogger can be used in Perfect( server-side-swift) project?

### ISSUE THREAD

**Issue by lovesomeone** [DaveWoodCom/XCGLogger#236]
Does XCGLogger can be used in Perfect( server-side-swift) project?

Because the Perfect project can be run in macOS and Linux  ,I don't know this XCGLogger  support in Linux

thank you!

**Comment by DaveWoodCom** [comment]
Hi.

I haven't tested XCGLogger with Perfect on macOS, but it should work.

I haven't added Linux support for XCGLogger yet because at the moment, I don't need it and so I wouldn't be dogfooding it enough for my liking. It's something I'd like to add later, but it'll likely be a feature I add when Swift 5.0 (or 6.0) comes out. Or if someone feels like sponsoring the feature.
