### ISSUE TITLE
Compile failure in FileDestination

### ISSUE THREAD

**Issue by leifashley** [DaveWoodCom/XCGLogger#238]
**Getting a build error for method openFile():**
fileManager.createFile(atPath: writeToFileURL.path, contents: nil, attributes: fileAttributes)

**Error:**
Cannot convert value of type '[FileAttributeKey : Any]?' to expected argument type '[String : Any]?'

Dropping back a rev for now :P

**Comment by DaveWoodCom** [comment]
Hi. This is the same issue as #232, #233 and others. It happens when you compile the library with Swift 3.x instead of 4.0. If you're still using Swift 3.x, please use 5.0.5.

If you're using CocoaPods, read https://www.cerebralgardens.com/blog/entry/2017/10/04/mix-and-match-swift-3-swift-4-libraries-with-cocoapods and see how you can update your Podfile to mix and match Swift 3.x and 4.0 libraries in the same project.

**Comment by leifashley** [comment]
Cool - thanks
