### ISSUE TITLE
[fixed]static libraries support 

### ISSUE THREAD

**Issue by AddIcechan** [DaveWoodCom/XCGLogger#280]
hope to support static libraries. 
 I use cocoapods v1.4, and my podfile support static libraries.  when I install , it show like this.

`
The Swift pod `XCGLogger` depends upon `ObjcExceptionBridging`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
`

**Comment by phimage** [comment]
did you try `pod 'XCGLogger', :modular_headers => true` or `pod 'XCGLogger', :modular_headers => false`
or try
`use_modular_headers!`

**Comment by AddIcechan** [comment]
I fixed it by add pod 'ObjcExceptionBridging', '~> 1.0.1',  :modular_headers => true

**Comment by DaveWoodCom** [comment]
Excellent, thanks for the update!

**Comment by stanmots** [comment]
Yes, this issue can be fixed by using `use_modular_headers!` flag. But the CocoaPods [docs](http://blog.cocoapods.org/CocoaPods-1.5.0/) suggest that the pod authors can add `'DEFINES_MODULE' => 'YES'` to `pod_target_xcconfig` so that the pod consumers won't need to add any configuration settings. 
It seems you just need to change [this line](https://github.com/DaveWoodCom/XCGLogger/blob/master/XCGLogger.podspec#L18) to make everyone happy:
`s.pod_target_xcconfig = { 'SWIFT_VERSION' => '5.0','DEFINES_MODULE' => 'YES' } `

**Comment by jbarros35** [comment]
what about if I don't want to migrate to swift 5.0 yet?
