### ISSUE TITLE
Has it been updated for more than a year?

### ISSUE THREAD

**Issue by HeebeLee** [DaveWoodCom/XCGLogger#316]
We are preparing for a new project, ready to use XCG logger. But I see more issues, and it seems that they haven't been updated for a long time. 
I don't know whether they are stable in the environment of XCode12 and Wwift 5.3+.

@DaveWoodCom Hi
Is there any new plan? If you can, please try to find time to update. Thank you very much.

**Comment by DaveWoodCom** [comment]
Hi @HeebeLee,

Yes, XCGLogger is still stable on the latest Xcode (including the latest beta). It hasn't need an update in over a year, and I tend not to push out frivolous updates just for the sake of an update.

If something breaks due to a change Apple makes, I'll work on a fix as soon as possible. For now, you can rest assured the current versions are working well.
