### ISSUE TITLE
Output to System Log

### ISSUE THREAD

**Issue by davidattias** [DaveWoodCom/XCGLogger#33]
It would be nice to have an option to output in device logs to be able to debug when the app is not attached to the debugger. 

I know I could use a file but it's not as convenient as doing a simple device log reading.

**Comment by DaveWoodCom** [comment]
Just an FYI, when I have a chance I'll add this option. Most likely for a version 2.0 (Swift 1.2).

**Comment by twobitlabs** [comment]
Having an option on XCGConsoleLogDestination to tell it to use NSLog instead of print would be great. In most of the apps we build we like to have info/warn/error go to the device's log and then verbose/debug only enabled when we're running/debugging from xcode.

**Comment by davidattias** [comment]
OK, thanks for the heads up.

**Comment by emaloney** [comment]
FYI, Gilt Groupe recently published a project called [CleanroomASL](https://github.com/emaloney/CleanroomASL) that provides a Swift API for writing to and reading from the Apple System Log.

You can use CleanroomASL to send messages to the Apple System Log so that they show up in the device console. (This is what `NSLog()` does that Swift's `print()` doesn't do, and it explains why the former shows up in the console and the latter does not.)

Note that [things behave a bit differently between the simulator and the device](https://github.com/emaloney/CleanroomASL#differences-between-the-device-and-simulator). I spent some time banging my head against ASL and interacting with it from Swift, so if I can answer some questions, let me know.

**Comment by DaveWoodCom** [comment]
I've added a 'XCGNSLogDestination' log destination that uses NSLog and will thus write to the console.

**Comment by davidattias** [comment]
Awesome! Thanks!
