### ISSUE TITLE
Append to log file instead of overwrite?

### ISSUE THREAD

**Issue by ryanweber88** [DaveWoodCom/XCGLogger#40]
Is there currently a way to just append logs to a log file instead of overwriting the file when re-opening the app?  If not, I'd love to see this functionality.

**Comment by allaire** [comment]
:+1:

**Comment by DaveWoodCom** [comment]
Just an FYI, when I have a chance I'll add this option. Most likely for a version 2.0 (Swift 1.2).

**Comment by ryanweber88** [comment]
Sound great, Dave.  For now, I just built a log rotator to circumvent the issue.  I'm excited to see this option in the future!

**Comment by mwaterfall** [comment]
👍

**Comment by mwaterfall** [comment]
@DaveWoodCom Any ETA on the Swift 1.2 version?

**Comment by neilt** [comment]
👍

**Comment by DaveWoodCom** [comment]
This is a fairly easy thing to add, but I'm concerned about making it too easy to use/forget and then have a log file that grows forever.

Curious what the advantage of this would be?

**Comment by ryanweber88** [comment]
Had a project recently where logs needed to persist forever.  Maybe, to mitigate the issue of an ever-growing single log file, split it up by day.  That's how my log rotator works, haven't had any problems thus far.

**Comment by neilt** [comment]
In Objective-C, we used CocoaLumberjack and logged to a file, even in released code.  In the release code the logger was set up to only log Errors and Warnings, while in Debug it logged everything.  The user, when experiencing a problem, has the option to send from the released application an email to us and the email would, with the users permission, include the log files plus other stuff.  In some of our applications we have ways for the user to increase the logging level, particularly in new applications.

In recent iOS releases we have been unable to get reliable access to our application's ASL logs because of sandboxing.  Apple claims that it is fixed but we've not had time to test again, and its been broken and fixed several times.

The problem for us is that we have no way to know when an iOS app is going to be killed and restarted.  That will wipe the log.  The solution should be very simple, but would require some form of log management.

Option 1: Specify the maximum number and size of log files to keep and rotate the log each time the logger is created or it reaches maximum size.

Option 2: Specify the maximum size of the log file and always append to the log, but removing earliest entries to keep under maximum size.

With either option, we would be ok periodically calling a log maintenance method that would check the log files and act accordingly.

**Comment by DaveWoodCom** [comment]
Thanks. I'll add this to my to do list then. Though I'll be honest, I'm swamped with other work so I wouldn't expect this anytime soon.

**Comment by neilt** [comment]
Thanks

**Comment by cwoloszynski** [comment]
Any updates on this feature?  This would be very valuable for my current project.  I'd like to suggest that a new init() function be added that has another flag to specify the type of log rotation desired (size, time) and number of rotations (history of files to keep). The logger would simply append a rotating integer (0..number of rotations-1) that is being used.  On launch the logger would append instead of overwrite the file.   This set of configurations should allow the developer to be successful without having the risk of an out-of-control design using too much cache space on the device.

**Comment by skreutzberger** [comment]
:+1:  for persistence.

Creating a log file per day sounds fine (yyyyMMdd.log or similar) and maybe let the use in the first iteration take care for cleanup. Currently I fix it in creating a log file per session / app start and cleaning up once in a while.

**Comment by cwoloszynski** [comment]
But the current code does not open 'append'; it opens overwrite.  Perhaps we can get a simpler design that does the 'open append', and 'change log file' functions in the library.  We could then develop using these changes. I could open with 'append' and set a daily timer to 'rotate' to new files and clean up old files per my need.  I'd use the filenames to be timestamps to simplify this design.

Is there interest in a pull request that implements this approach?

**Comment by DaveWoodCom** [comment]
The reason I haven't done this yet, is that if feels like a log rotation system could be it's own framework in itself, that XCGLogger could use. Still evaluating that though.

**Comment by skreutzberger** [comment]
Can you please give us at least the option to append to a file instead of always overwriting? I tried to do it by myself with NSOutputStreams but gosh, it gets messy quickly :)

**Comment by cwoloszynski** [comment]
I've offered a pull request to implement the simplest design discussed.  In case it is of interest to anyone else.

**Comment by neilt** [comment]
Log rotation may be a framework in itself, but blindly overwriting is, IMO, a bug and makes the functionality nearly useless.  I also offered a pull request that just renames the existing file to .bak and starts a new one.  The base functionality should at lest either append or create a single backup and expose the file name and path. Huge progress can be made here without overthinking and a lot of complexity.

**Comment by klaas** [comment]
+1 for appending to existing file

**Comment by Gerst20051** [comment]
:+1:

**Comment by Laban1** [comment]
I could also REALLY use append to existing file!  Just make it optional and do not worry about the log growing out of control - it will be up to the person using it to handle that or simply not use the append option.

**Comment by neilt** [comment]
I use the following to rename the current file to a backup when the logger starts.  This preserves the log in case of a crash and restart.

```
diff --git a/XCGLogger/Library/XCGLogger/XCGLogger.swift b/XCGLogger/Library/XCGLogger/XCGLogger.swift
index bed615a..4868d0d 100644
--- a/XCGLogger/Library/XCGLogger/XCGLogger.swift
+++ b/XCGLogger/Library/XCGLogger/XCGLogger.swift
@@ -238,7 +238,7 @@ public class XCGNSLogDestination: XCGBaseLogDestination {
 public class XCGFileLogDestination: XCGBaseLogDestination {
     // MARK: - Properties
     public var logQueue: dispatch_queue_t? = nil
-    private var writeToFileURL: NSURL? = nil {
+    private(set) var writeToFileURL: NSURL? = nil {
         didSet {
             openFile()
         }
@@ -275,6 +275,23 @@ public class XCGFileLogDestination: XCGBaseLogDestination {
 
         if let writeToFileURL = writeToFileURL,
             let path = writeToFileURL.path {
+                let backupPath = path + ".bak"
+                if NSFileManager.defaultManager().fileExistsAtPath(backupPath) {
+                    do {
+                        try NSFileManager.defaultManager().removeItemAtPath(backupPath)
+                    }
+                    catch _ as NSError {
+                        // really don't need to do anything
+                    }
+                }
+                if NSFileManager.defaultManager().fileExistsAtPath(path) {
+                    do {
+                        try NSFileManager.defaultManager().moveItemAtPath(path, toPath: backupPath)
+                    }
+                    catch _ as NSError {
+                        // really don't need to do anything
+                    }
+                }
                 
                 NSFileManager.defaultManager().createFileAtPath(path, contents: nil, attributes: nil)
                 do {
```

**Comment by neilt** [comment]
To always append change:
```
                do {
                    logFileHandle = try NSFileHandle(forWritingToURL: writeToFileURL)
                }
```

to

```
                do {
                    logFileHandle = try NSFileHandle(forUpdatingAtPath: writeToFileURL)
                }
```

**Comment by neilt** [comment]
I deleted my suggested code for appending as it is more involved than the one line of code to open the file for updating.  Sorry for the noise, too early in the morning.

**Comment by xyzisinus** [comment]
Thank you for the great package.  Vote for the ability to append with a configurable maximum size.  Thanks again!

**Comment by drbarto** [comment]
:+1:
Really a great log lib, but without appending to log files I don't get the point of writing to a file at all; since the app could die any second, I have no secure way of backing up manually, so why even bother to persist locally?
I often use logging to track bugs; now if a bug crashed the app, I'd like the user to restart and send me the log file. If the log is basically cleared on startup, obviously this can't work.

**Comment by DaveWoodCom** [comment]
Hi guys/gals. I'm working on the next version that will include log rotation among other things. Plan is to have it out soonish.

**Comment by AlexGauthier** [comment]
:+1: really good news!

**Comment by xyzisinus** [comment]
Great to hear!  Thanks!

**Comment by neilt** [comment]
Excellent, excellent, excellent.

**Comment by MiguelChiang** [comment]
Great, looking forward to it!

**Comment by shobhanaquickride** [comment]
Thank you! Looking forward to it!

**Comment by chrisjones-tripletri** [comment]
Also needed the ability to append to an existing file (not a log rotation framework).   For what its worth, I was able to work around it for now by modifying the file open code in my local copy as follows:

```
            +if( !NSFileManager.defaultManager().fileExistsAtPath(path)) {
                NSFileManager.defaultManager().createFileAtPath(path, contents: nil, attributes: nil)
            +}
            do {
                logFileHandle = try NSFileHandle(forWritingToURL: writeToFileURL)
            +    logFileHandle?.seekToEndOfFile()
            }
```
Thanks for the library!

**Comment by CH3821** [comment]
Looking forward to it! thanks

**Comment by DaveWoodCom** [comment]
Done (available with advanced usage only).

When creating your `XCGFileLogDestination` object, include a `shouldAppend:` option, set to `true`. You can also include an `appendMarker:` string to add a marker to the file to indicate where the append happened. Set it to `nil` to not add the marker. Omit it and you'll get a default marker of `-- ** ** ** --`

**Comment by xyzisinus** [comment]
Thank you so much!
