### ISSUE TITLE
xCode 6.3

### ISSUE THREAD

**Issue by Ged2323** [DaveWoodCom/XCGLogger#48]
Hi,

I only just updated to xCode 6.3 today.  Oh man what a nightmare! Anyways your XCGLogger was working great in 6.2 though now it's doing the below.

The log message is corrupt.
I was trying to print this:

log.info("——>saveButtonClicked ")

Though I'm getting:

2015-04-10 12:47:13.133 [Info] [LocationSettingsUITable.swift:96] saveButtonClickedi(n)d:e x\342 \200i\224s\342 \2000\224
>saivnedBeuxt tiosn C1l
icked 

Any ideas how to fix this or where to look I'm happy to help.

Yours Sincerely
Gerard Grundy

**Comment by DaveWoodCom** [comment]
This looks like you have other `println()` calls. `println()` is not thread safe, so if you have multiple calls on different threads, they will write on top of each other, just like you're seeing there.

XCGLogger uses a queue in order to ensure all `println()` calls happen in sequence, and complete before the next one, but obviously can't control other places in your code that uses `println()`.
