### ISSUE TITLE
Replacement for deprecated debugExec functions

### ISSUE THREAD

**Issue by steilerDev** [DaveWoodCom/XCGLogger#51]
I like the idea and efficient usage of auto closures on your log messages and I understand why you deprecate the debugExec functions. Unfortunately I used this functionality mainly to let my application crash in specific scenarios, which should not happen in a production app using the following mechanism:

`logger.debugExec { abort() } `

Currently I only got the deprecated warning but if I want to comply with your newest version I had to change my function to sth like

`logger.debug { abort(); return nil }`

which produces a warning since the return statement is never reached (which is very true).

I would welcome if you could (re-) introduce a debug function which is not expecting any return value (just like debugExec). Of course I like the concise syntax of only using debug, so you could just overload this function a little bit.

Thanks!

**Comment by DaveWoodCom** [comment]
Hmm, I spent all last weekend debating with myself over whether to deprecate those methods. I had a feeling there'd be some use for them that wasn't covered with the new methods. Unfortunately, there's no way to overload the methods where there only difference is the return value. That's why I went with the optional String so you could at least avoid having to return a string. That doesn't help with your case though.

I'll un-deprecate those functions.

**Comment by steilerDev** [comment]
Why isn't it possible to add a signature like this:

`public class func info(functionName: String = __FUNCTION__, fileName: String = __FILE__, lineNumber: Int = __LINE__, closure: () -> ())`

this would remove the exec functions, keep a simple syntax and still offer the possibility to execute a function without return value.

**Comment by DaveWoodCom** [comment]
Undeprecated the *Exec() functions in version 2.1
