### ISSUE TITLE
Background thread logging

### ISSUE THREAD

**Issue by JaviSoto** [DaveWoodCom/XCGLogger#84]
Hey!

Great framework :) I really love it.

I just integrated it, and noticed that all the logging happens on the main thread. I haven't profiled, and it's likely not to be the bottle neck for my application at the moment. However I think it would be nice to configure, especially if we want to do some more verbose logging. Would this make sense?

**Comment by DaveWoodCom** [comment]
Thanks. That's an interesting point. The `master` branch is currently using a queue to process all of the log calls. This was needed because `print()` wasn't thread safe until Swift 2.0. I found that using the queue while debugging had the side effect that breakpoints right after a log message would trigger, before the log message was printed to the console, making it hard to see the results of the log when you needed it. On the `swift_2.0` branch I was able to remove the queue because `print()` is now (apparently) thread safe, this makes debugging much better. It also means the closures for the log will be processed on whatever thread the call is made on.

I can see your point about having the logs processed on a background thread when you're not actually debugging though, so when I get some time, I'll add a queue option back into the 2.0 branch.

Thanks!

BTW, are you using the framework at Twitter, or just personal projects? I'd love to start adding some "Trusted by ABC Corp" type blurbs in the ReadMe.

**Comment by JaviSoto** [comment]
That sounds perfect :) 

>BTW, are you using the framework at Twitter, or just personal projects? I'd love to start adding some "Trusted by ABC Corp" type blurbs in the ReadMe.

I can't really answer that question right now, but I'll let you know when that changes :)

**Comment by skreutzberger** [comment]
I opened a pull request which moves all output methods in a background thread. https://github.com/DaveWoodCom/XCGLogger/pull/89

**Comment by DaveWoodCom** [comment]
Unfortunately that PR moves all output to the background thread. This is the way it used to be, but actually is a pain when debugging. I plan to make it an option to use the background, not the default.

**Comment by skreutzberger** [comment]
Even better, thanks! You can decline the PR :)

**Comment by DaveWoodCom** [comment]
This is now in the master branch. It's an option for the included log destinations. You can set the `logQueue` property to a dispatch queue and it'll use it. Leave it as nil and it'll stay on the current thread. This lets you customize by destination, so you can for example have the console show the log instantly, and still push the file log to the background. Mostly useful for keeping logs on the current thread while in DEBUG mode and pushing to the background for a RELEASE mode.
