### ISSUE TITLE
Console logging in release build

### ISSUE THREAD

**Issue by sust86** [DaveWoodCom/XCGLogger#92]
Hi Dave, great job so far.. I do really like your simple frame!

Would it make sense to disable console logging in XCGLogger for release builds?

Managing it in the setup() method can get very annoying when creating many different loggers and I couldn't successful override the default print / println methods for release builds.

Thanks!

**Comment by DaveWoodCom** [comment]
Hey @sust86, thanks!

Same question just came up on StackOverflow http://stackoverflow.com/a/32803828/144857 , so I'll just repeat it here.

First, I'd wonder if you really want to completely disable logs in production. using `error` and `severe` logs can be useful diagnostic tools for released apps.

If you do however want to completely eliminate logs in production, I would recommend altering the way you set up and use the logger than what I have in the official docs.

Change the global log object to be an optional instead:

    let log: XCGLogger? = {
        #if DEBUG
            let log = XCGLogger.defaultInstance()
            log.setup(.Debug, showThreadName: true, showLogLevel: true, showFileNames: true, showLineNumbers: true, writeToFile: nil, fileLogLevel: .Debug)
            return log
        #else
            return nil
        #endif
    }

Then change your log calls to:

    log?.debug("whatever")

This will eliminate any overhead of the logger since `log` will be `nil` in production and no logging calls will ever be made.

Also, you could (and I plan to at some point), add remote logging so `error` and `severe` logs are reported to your server or something.
